name: Lint w/ ruff

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      # Include `--output-format=github` to enable automatic inline annotations.
      - name: Run Ruff
        run: ruff check --output-format=github .
