name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.9, 3.11.5, 3.12, 3.13]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.27"
      
      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}
      
      - name: Install the project
        run: uv sync --all-extras --dev
      
      - name: Tests
        run: make test

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "0.5.27"

      - name: Set up Python
        run: uv python install 3.13

      - name: Build
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
